# Create ConfigMap for docker credentials
apiVersion: v1
kind: ConfigMap
metadata:
    name: appname-someid-docker-config
    namespace: kaniko
data:
  config.json: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "base64encoded(username:password)"
        }
      }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: appname-someid-kaniko-build
  namespace: kaniko
spec:
  restartPolicy: Never
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:v1.9.2
      imagePullPolicy: IfNotPresent
      args:
        - --dockerfile=Dockerfile
        - --context=/workdir/app-src
        - --snapshot-mode=redo
        - --destination=docker.io/yusufs/scraping-ig:tag-from-kaniko
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      volumeMounts:
        # Mount docker.json config to /kaniko/.docker/config.json
        - mountPath: /kaniko/.docker/
          name: docker-config
        # Mount all files inside workdir to /workdir.
        # This should contain application code.
        - mountPath: /workdir
          name: workdir
  initContainers:
    # Clone with HTTPS mode.
    # If you use GitHub, see https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
    - name: git-clone
      image: docker.io/bitnami/git:2
      imagePullPolicy: IfNotPresent
      args:
        - git
        - clone
        - https://username:password@github.com/yusufsyaifudin/scraping-ig.git
        - /workdir/app-src
      volumeMounts:
        - mountPath: /kaniko/.docker/
          name: docker-config
        - mountPath: /workdir
          name: workdir
      resources:
        limits:
          cpu: 200m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 50Mi
    - name: git-checkout
      image: docker.io/bitnami/git:2
      imagePullPolicy: IfNotPresent
      args:
        - git
        - -C
        - /workdir/app-src
        - checkout
        - 9dc22bf33f00e2bcf5dc31fb0d476b55041d01d4
      volumeMounts:
        - mountPath: /kaniko/.docker/
          name: docker-config
        - mountPath: /workdir
          name: workdir
      resources:
        limits:
          cpu: 200m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 50Mi
  volumes:
    - configMap:
        defaultMode: 420
        name: appname-someid-docker-config
      name: docker-config
    - emptyDir: {}
      name: workdir
