apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: loki-reader
spec:
  parallelism: 1
  separate: false
  script:
    configMap:
      name: loki-reader
      file: reader.js
  arguments: -o json=reader_query30m.json --console-output /home/k6/reader_query30m.log --env LOKI_URL=https://grafana-loki-gateway.domain.io --env TENANT_ID=devops-production-alicloud
  runner:
    image: grafana/k6:0.47.0
    securityContext:
      runAsUser: 12345
      runAsGroup: 12345
      runAsNonRoot: true
      fsGroup: 12345
    resources:
      limits:
        cpu: 2000m
        memory: 2Gi
      requests:
        cpu: 1000m
        memory: 1Gi
    volumeMounts:
      - name: home-dir
        mountPath: "/home/k6"
    volumes:
      - name: home-dir
        persistentVolumeClaim:
          claimName: result-storage
