apiVersion: v1
kind: Pod
metadata:
  name: dataaccess
spec:
  containers:
    - image: alpine:3.18.4
      name: alpine
      command: ['sleep', 'infinity']
      volumeMounts:
        - name: k6-result
          mountPath: /home/k6
  volumes:
    - name: k6-result
      persistentVolumeClaim:
        claimName: result-storage