apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: result-storage
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
    - ReadOnlyMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: your-storage-class-name
