# Create ConfigMap for docker credentials
apiVersion: v1
kind: ConfigMap
metadata:
  name: appname-someid-docker-config
  namespace: buildkit
data:
  config.json: |
    {
      "auths": {
        "https://index.docker.io/v1/": {
          "auth": "base64encoded(username:password)"
        }
      }
    }

---
apiVersion: v1
kind: Pod
metadata:
  name: appname-someid-buildkit-build
  namespace: buildkit
spec:
  restartPolicy: Never
  # https://github.com/moby/buildkit/tree/v0.12.4?tab=readme-ov-file#building-a-dockerfile-with-buildctl
  containers:
    - name: buildkit
      image: docker.io/moby/buildkit:v0.12.4
      imagePullPolicy: IfNotPresent
      command:
        # https://github.com/moby/buildkit/tree/v0.12.4?tab=readme-ov-file#daemonless
        - buildctl-daemonless.sh
      args:
        - build
        - --frontend
        - dockerfile.v0
        # --local exposes local source files from client to the builder.
        # context and dockerfile are the names Dockerfile frontend looks for build context and Dockerfile location.
        - --local
        - context=/workdir/app-src
        - --local
        - dockerfile=/workdir/app-src
        - --output
        - type=image,name=docker.io/yusufs/scraping-ig:tag-from-buildkit,push=true
      resources:
        limits:
          cpu: 1000m
          memory: 2Gi
        requests:
          cpu: 500m
          memory: 1Gi
      volumeMounts:
        # Mount docker.json config to /root/.docker/config.json
        - mountPath: /root/.docker/
          name: docker-config
        # Mount all files inside workdir to /workdir.
        # This should contain application code.
        - mountPath: /workdir
          name: workdir
      securityContext:
        privileged: true
  initContainers:
    # Clone with HTTPS mode.
    # If you use GitHub, see https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens
    - name: git-clone
      image: docker.io/bitnami/git:2
      imagePullPolicy: IfNotPresent
      args:
        - git
        - clone
        - https://username:password@github.com/yusufsyaifudin/scraping-ig.git
        - /workdir/app-src
      volumeMounts:
        - mountPath: /root/.docker/
          name: docker-config
        - mountPath: /workdir
          name: workdir
      resources:
        limits:
          cpu: 200m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 50Mi
    - name: git-checkout
      image: docker.io/bitnami/git:2
      imagePullPolicy: IfNotPresent
      args:
        - git
        - -C
        - /workdir/app-src
        - checkout
        - 9dc22bf33f00e2bcf5dc31fb0d476b55041d01d4
      volumeMounts:
        - mountPath: /root/.docker/
          name: docker-config
        - mountPath: /workdir
          name: workdir
      resources:
        limits:
          cpu: 200m
          memory: 100Mi
        requests:
          cpu: 100m
          memory: 50Mi
  volumes:
    - configMap:
        defaultMode: 420
        name: appname-someid-docker-config
      name: docker-config
    - emptyDir: {}
      name: workdir
